Adv_lamda: 1
Corr_lamda: 20
Cyc_lamda: 10
Smooth_lamda: 10
batchSize: 30
bidirect: false
checkpoint: checkpoint/Regression_Short_best_netG_A2B.pth
cuda: true
dataroot: data/Regression/Short-term
decay_epoch: 20
epoch: 0
image_save: output/Long-term/pred
image_save1: output/Long-term/before
image_save2: output/Long-term/after
input_nc: 1
lr: 0.0001
n_cpu: 1
n_epochs: 200
name: CycleGan
noise_level: 1
output_nc: 1
port: 6019
regist: true
save_root: output/Short-term/
size: 256
type: classifier
val_dataroot: data/Regression/Short-term
